"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { Flowbite } from "flowbite-react";
import theme from "@/app/flowbite-theme";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Polyclinic Server",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Flowbite theme={{ theme }}>{children}</Flowbite>
      </body>
    </html>
  );
}
